#!/usr/bin/with-contenv bash

# make our folders
mkdir -p \
	/config/{nginx/site-confs,www,log/nginx,log/php,php} \
	/run \
	/var/lib/nginx/tmp/client_body \
	/var/tmp/nginx

# copy config files
[[ ! -f /config/nginx/nginx.conf ]] && \
	cp /defaults/nginx.conf /config/nginx/nginx.conf
[[ ! -f /config/nginx/site-confs/default ]] && \
	cp /defaults/default /config/nginx/site-confs/default
[[ $(find /config/www -type f | wc -l) -eq 0 ]] && \
	cp /defaults/index.php /config/www/index.php

# create local php.ini if it doesn't exist, set local timezone
[[ ! -f /config/php/php-local.ini ]] && \
	printf "; Edit this file to override php.ini directives and restart the container\\n\\ndate.timezone = %s\\n" "$TZ" > /config/php/php-local.ini
# copy user php-local.ini to image
cp /config/php/php-local.ini /etc/php7/conf.d/php-local.ini
#fix php-fpm log to stderr
sed -i "s#;error_log = log/php7/error.log.*#error_log = /dev/stderr#g" /etc/php7/php-fpm.conf
#fix php-fpm PATH
echo "env[PATH] = /usr/local/bin:/usr/bin:/bin" >> /etc/php7/php-fpm.conf
#fix php-fpm user
sed -i "s#user = nobody.*#user = abc#g" /etc/php7/php-fpm.d/www.conf
sed -i "s#group = nobody.*#group = abc#g" /etc/php7/php-fpm.d/www.conf
#fix php-fpm clean_env to allow access to ENVs
sed -i 's/;clear_env = no/clear_env = no/g' /etc/php7/php-fpm.d/www.conf
#fix php-fpm to have a static single worker
sed -i 's/pm = dynamic/pm = static/' /etc/php7/php-fpm.d/www.conf
sed -i 's/pm.max_children = 5/pm.max_children = 1/' /etc/php7/php-fpm.d/www.conf
# create override for www.conf if it doesn't exist
[[ ! -f /config/php/www2.conf ]] && \
	printf "; Edit this file to override www.conf and php-fpm.conf directives and restart the container\\n\\n; Pool name\\n[www]\\n\\n" > /config/php/www2.conf
# copy user www2.conf to image
cp /config/php/www2.conf /etc/php7/php-fpm.d/www2.conf

# enable/disable http trace logs

if [[ -z "$HTTP_TRACE" || "$HTTP_TRACE" == "false" ]]; then
  echo "**** Disable HTTP Trace ****"
  sed -i 's%access_log /dev/stdout;%access_log off;%g' /config/nginx/nginx.conf;
else
  echo "**** Enable HTTP Trace ****"
  sed -i 's%access_log off;%access_log /dev/stdout;%g' /config/nginx/nginx.conf;
fi

# permissions
chown -R abc:abc \
	/config \
	/var/lib/nginx \
	/var/tmp/nginx
chmod -R g+w \
	/config/{nginx,www}
